name: gallery_app
description: Test project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.1.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  flutter_bloc: ^8.1.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.3.1
  dart_code_metrics: ^5.7.4
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  rxdart: ^0.27.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  auto_route_generator: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText/SFUIDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/SFUIText/SFUIText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFUIText/SFUIText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIText/SFUIText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText/SFUIText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIText/SFUIText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIText/SFUIText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIText/SFUIDisplay-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFUIText/SFUIDisplay-Thin.ttf
          weight: 100
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
       
       
      
      
       
       
       
        
      
       